In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\hp\Projects\ecommerce-data-analytics-ml\data\Ecommerce_Sales_Data.csv')

In [3]:
df['order_date'] = pd.to_datetime(df['order_date'],dayfirst=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5000 non-null   int64
 1   order_date     5000 non-null   datetime64[ns]
 2   customer_name  5000 non-null   object
 3   region         5000 non-null   object
 4   city           5000 non-null   object
 5   category       5000 non-null   object
 6   sub_category   5000 non-null   object
 7   product_name   5000 non-null   object
 8   quantity       5000 non-null   int64
 9   unit_price     5000 non-null   int64
 10  discount       5000 non-null   int64
 11  sales          5000 non-null   float64
 12  profit         5000 non-null   float64
 13  payment_mode   5000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 547.0+ KB

In [5]:
df.isnull().sum()

order_id         0
order_date       0
customer_name    0
region           0
city             0
category         0
sub_category     0
product_name     0
quantity         0
unit_price       0
discount         0
sales            0
profit           0
payment_mode     0
dtype: int64

In [6]:
df.head()

,order_id,order_date,customer_name,region,city,category,sub_category,product_name,quantity,unit_price,discount,sales,profit,payment_mode
0,10001,2024-10-19,Kashvi Varty,South,Bangalore,Books,Non-Fiction,Non-Fiction Ipsum,2,36294,5,68958.6,10525.09,Debit Card
1,10002,2025-08-30,Advik Desai,North,Delhi,Groceries,Rice,Rice Nemo,1,42165,20,33732.0,6299.66,Debit Card
2,10003,2023-11-04,Rhea Kalla,East,Patna,Kitchen,Juicer,Juicer Odio,4,64876,20,207603.2,19850.27,Credit Card
3,10004,2025-05-23,Anika Sen,East,Kolkata,Groceries,Oil,Oil Doloribus,5,37320,15,158610.0,36311.02,UPI
4,10005,2025-01-19,Akarsh Kaul,West,Pune,Clothing,Kids Wear,Kids Wear Quo,1,50037,10,45033.3,9050.04,Debit Card

# Total revenue

In [7]:
total_revenue = df['sales'].sum()
total_revenue

np.float64(533666024.35)

The total revenue from all sales is ₹53.37 crore.
It matters for overall business growth

# Monthly revenue trend

In [8]:
df['Year_Month'] = df['order_date'].dt.to_period('M')

In [9]:
df.groupby('Year_Month')['sales'].sum().reset_index()

   Year_Month        sales
0     2023-10  21307522.20
1     2023-11  22040269.20
2     2023-12  20624240.25
3     2024-01  21477241.40
4     2024-02  19853396.50
5     2024-03  21571015.35
6     2024-04  22214781.10
7     2024-05  24744786.55
8     2024-06  21368962.50
9     2024-07  24019283.90
10    2024-08  23299894.50
11    2024-09  22480182.05
12    2024-10  23607626.65
13    2024-11  22036247.55
14    2024-12  24806786.40
15    2025-01  21520801.80
16    2025-02  19902446.10
17    2025-03  22602988.75
18    2025-04  21653817.90
19    2025-05  26010928.65
20    2025-06  21155496.20
21    2025-07  22526567.55
22    2025-08  23317916.20
23    2025-09  18131496.70
24    2025-10   1391328.40

It shows monthly revenue and helps tu understand the patterns how the revenue is increasiong or decreasing

# Top 10 products by revenue

In [11]:
df.groupby('product_name')['sales'].sum().sort_values(ascending=False).reset_index().head(10)

              product_name      sales
0   Headphones Accusantium  857184.20
1         Spices Quibusdam  687651.25
2  Accessories Repellendus  687083.30
3              Bed Tenetur  670994.80
4         Laptop Similique  666640.60
5                Lamp Enim  665920.20
6          Shampoo Commodi  659546.60
7           Lamp Veritatis  652909.50
8  Men's Wear Voluptatibus  649048.00
9           Textbook Omnis  633246.25

Displays the Top 10 products by revenue helps to find the best selling and demanding product